# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ".git|.venv|venv|var|docker"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        exclude: "profiles-sample.pem"
      - id: fix-byte-order-marker
      - id: debug-statements
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --preview]
        types: [python]
      - id: ruff-format
